package com.plasticaudit.entity;

import jakarta.persistence.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * AuditReport Entity — maps to the 'audit_reports' table.
 * Generated by the multithreaded ReportAggregatorService (CO1).
 * Contains aggregate plastic waste metrics — SDG 12 & 14 key metrics.
 */
@Entity
@Table(name = "audit_reports")
public class AuditReport {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // CO3: @ManyToOne — Report belongs to an Industry
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "industry_id", nullable = false)
    private Industry industry;

    // CO3: @ManyToOne — Report generated by a User (admin)
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "generated_by_user_id")
    private User generatedBy;

    @Column(name = "period_start", nullable = false)
    private LocalDate periodStart;

    @Column(name = "period_end", nullable = false)
    private LocalDate periodEnd;

    @Column(name = "total_generated_kg", nullable = false)
    private Double totalGeneratedKg = 0.0;

    @Column(name = "total_recycled_kg", nullable = false)
    private Double totalRecycledKg = 0.0;

    @Column(name = "total_eliminated_kg", nullable = false)
    private Double totalEliminatedKg = 0.0;

    @Column(name = "reduction_rate_percent")
    private Double reductionRatePercent = 0.0; // SDG 12 Key Metric

    @Column(name = "recycling_ratio_percent")
    private Double recyclingRatioPercent = 0.0; // SDG 14 Key Metric

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private ReportStatus status = ReportStatus.DRAFT;

    @Column(name = "generated_at")
    private LocalDateTime generatedAt;

    @Column(name = "remarks", length = 1000)
    private String remarks;

    @PrePersist
    public void prePersist() {
        this.generatedAt = LocalDateTime.now();
    }

    public enum ReportStatus {
        DRAFT, PENDING_REVIEW, APPROVED, REJECTED
    }

    // ── Constructors ────────────────────────────────────────
    public AuditReport() {
    }

    // ── Getters & Setters ───────────────────────────────────
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Industry getIndustry() {
        return industry;
    }

    public void setIndustry(Industry industry) {
        this.industry = industry;
    }

    public User getGeneratedBy() {
        return generatedBy;
    }

    public void setGeneratedBy(User generatedBy) {
        this.generatedBy = generatedBy;
    }

    public LocalDate getPeriodStart() {
        return periodStart;
    }

    public void setPeriodStart(LocalDate periodStart) {
        this.periodStart = periodStart;
    }

    public LocalDate getPeriodEnd() {
        return periodEnd;
    }

    public void setPeriodEnd(LocalDate periodEnd) {
        this.periodEnd = periodEnd;
    }

    public Double getTotalGeneratedKg() {
        return totalGeneratedKg;
    }

    public void setTotalGeneratedKg(Double totalGeneratedKg) {
        this.totalGeneratedKg = totalGeneratedKg;
    }

    public Double getTotalRecycledKg() {
        return totalRecycledKg;
    }

    public void setTotalRecycledKg(Double totalRecycledKg) {
        this.totalRecycledKg = totalRecycledKg;
    }

    public Double getTotalEliminatedKg() {
        return totalEliminatedKg;
    }

    public void setTotalEliminatedKg(Double totalEliminatedKg) {
        this.totalEliminatedKg = totalEliminatedKg;
    }

    public Double getReductionRatePercent() {
        return reductionRatePercent;
    }

    public void setReductionRatePercent(double reductionRatePercent) {
        this.reductionRatePercent = reductionRatePercent;
    }

    public Double getRecyclingRatioPercent() {
        return recyclingRatioPercent;
    }

    public void setRecyclingRatioPercent(double recyclingRatioPercent) {
        this.recyclingRatioPercent = recyclingRatioPercent;
    }

    public ReportStatus getStatus() {
        return status;
    }

    public void setStatus(ReportStatus status) {
        this.status = status;
    }

    public LocalDateTime getGeneratedAt() {
        return generatedAt;
    }

    public void setGeneratedAt(LocalDateTime generatedAt) {
        this.generatedAt = generatedAt;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}
